import Head from "next/head";
import Avatar from "../components/Avatar";
import {
  ViewGridIcon,
  MicrophoneIcon,
  SearchIcon,
} from "@heroicons/react/solid";
import Image from "next/image";
import Footer from "../components/Footer";
import { useRef } from "react";
import { useRouter } from "next/dist/client/router";

export default function Home() {
  const router = useRouter();
  const searchRefInput = useRef(null);
  const search = (e) => {
    e.preventDefault();
    const term = searchRefInput.current.value;
    if (!term) return;

    router.push(`/search?term=${term}`);
  };
  return (
    <div className="flex flex-col justify-center h-screen">
      <Head>
        <title>Google Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <header className="flex w-full p-3 justify-between text-sm text-gray-700">
        {/* Left */}
        <div className="flex space-x-4 items-center">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>

        {/* Right */}
        <div className="flex space-x-4 items-center">
          <p className="link">Gmail</p>
          <p className="link">Image</p>
          <ViewGridIcon className="w-10 h-10 p-2 rounded-full hover:bg-gray-100 cursor-pointer" />
          <Avatar url="https://icons-for-free.com/iconfiles/png/512/avatar+person+profile+user+icon-1320166578424287581.png" />
        </div>
      </header>

      {/* Body */}
      <form
        className="flex flex-col mt-20  items-center flex-grow"
        onSubmit={search}
      >
        <Image
          src="https://www.google.co.uz/images/branding/googlelogo/2x/googlelogo_color_160x56dp.png"
          height={100}
          width={300}
          alt="important"
        />
        <div
          className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md border
        border-gray-200 rounded-full px-5 py-3 items-center sm:maw-w-xl lg:max-w-2xl"
        >
          <SearchIcon className="h-5 mr-3 text-gray-500" />
          <input
            ref={searchRefInput}
            type="text"
            className="focus:outline-none flex-grow w-4/4"
          />
          <MicrophoneIcon className="h-5" />
        </div>
        <div className="flex flex-col w-1/2  space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4">
          <button onClick={search} className="btn">
            Google Search
          </button>
          <button onClick={search} className="btn">
            I am feeling Lucky
          </button>
        </div>
      </form>
      {/* Footer */}
      <Footer />
    </div>
  );
}
